version: 1
formatters:
  simple:
    format: '%(asctime)s - {%(filename)s:%(lineno)d} - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%H:%M:%S'
  user:
    format: '%(asctime)s - %(name)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: user
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logfile.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
root:
  level: DEBUG
  handlers:
   - file
